services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: srb_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    ports:
      - "5432:5432"